// conponents/classification/classification.js
Component({
  /**
   * 组件的属性列表
   */
  properties: {
    hugong:{
      type:Array
    },
   
  },

  /**
   * 组件的初始数据
   */
  data: {
    flag: 0,
    flagIndex:0,
    arrli:[
      {
        name:"病人陪护",
        id:1
      },
      {
        name:"平台认证",
        id:2
      },
      {
        name:"产妇陪护",
        id:3
      },
      {
        name:"产妇陪护",
        id:3
      },
      {
        name:"产妇陪护",
        id:3
      },
      {
        name:"产妇陪护",
        id:3
      },
    ],
    arr:[
      {
        title:"金牌保姆",
        id:0
      },
      {
        title:"金牌护工",
        id:1
      },
      {
        title:"金牌保护",
        id:2
      },
      {
        title:"金牌保护",
        id:3
      },
      {
        title:"金牌保护",
        id:4
      },
      {
        title:"金牌保护",
        id:5
      },
    ],
    list:[
      {
        img:'../../img/mipmap-mdpi/5bcf6403efb3d.png',
        fuwu:"可服务",
        name:"张阿姨",
        zuizao:"最早可约3月1号",
        yi:"以服务100人",
        dingwei:"../../img/mipmap-mdpi/dingwei.png",
        weizhi:"蜀都中心一期",
        qianmi:"0.1km"
      },
      {
        img:'../../img/mipmap-mdpi/5bcf6403efb3d.png',
        fuwu:"可服务",
        name:"张阿姨",
        zuizao:"最早可约3月1号",
        yi:"以服务100人",
        dingwei:"../../img/mipmap-mdpi/dingwei.png",
        weizhi:"蜀都中心一期",
        qianmi:"0.1km"
      },
      {
        img:'../../img/mipmap-mdpi/5bcf6403efb3d.png',
        fuwu:"可服务",
        name:"张阿姨",
        zuizao:"最早可约3月1号",
        yi:"以服务100人",
        dingwei:"../../img/mipmap-mdpi/dingwei.png",
        weizhi:"蜀都中心一期",
        qianmi:"0.1km"
      },
      {
        img:'../../img/mipmap-mdpi/5bcf6403efb3d.png',
        fuwu:"可服务",
        name:"张阿姨",
        zuizao:"最早可约3月1号",
        yi:"以服务100人",
        dingwei:"../../img/mipmap-mdpi/dingwei.png",
        weizhi:"蜀都中心一期",
        qianmi:"0.1km"
      },
      {
        img:'../../img/mipmap-mdpi/5bcf6403efb3d.png',
        fuwu:"可服务",
        name:"张阿姨",
        zuizao:"最早可约3月1号",
        yi:"以服务100人",
        dingwei:"../../img/mipmap-mdpi/dingwei.png",
        weizhi:"蜀都中心一期",
        qianmi:"0.1km"
      },
    ],
    jigou:[
      {
        img:"../../img/mipmap-mdpi/logo.png",
        name:"成都好姐姐陪护服务有限公司",
        title:"以服务1000人",
        dingwei:"../../img/mipmap-mdpi/dingwei.png",
        weizhi:"蜀都中心一期",
        qianmi:"0.1km"
      },
      {
        img:"../../img/mipmap-mdpi/logo.png",
        name:"成都好姐姐陪护服务有限公司",
        title:"以服务1000人",
        dingwei:"../../img/mipmap-mdpi/dingwei.png",
        weizhi:"蜀都中心一期",
        qianmi:"0.1km"
      },
      {
        img:"../../img/mipmap-mdpi/logo.png",
        name:"成都好姐姐陪护服务有限公司",
        title:"以服务1000人",
        dingwei:"../../img/mipmap-mdpi/dingwei.png",
        weizhi:"蜀都中心一期",
        qianmi:"0.1km"
      },
      {
        img:"../../img/mipmap-mdpi/logo.png",
        name:"成都好姐姐陪护服务有限公司",
        title:"以服务1000人",
        dingwei:"../../img/mipmap-mdpi/dingwei.png",
        weizhi:"蜀都中心一期",
        qianmi:"0.1km"
      },
      {
        img:"../../img/mipmap-mdpi/logo.png",
        name:"成都好姐姐陪护服务有限公司",
        title:"以服务1000人",
        dingwei:"../../img/mipmap-mdpi/dingwei.png",
        weizhi:"蜀都中心一期",
        qianmi:"0.1km"
      },
      {
        img:"../../img/mipmap-mdpi/logo.png",
        name:"成都好姐姐陪护服务有限公司",
        title:"以服务1000人",
        dingwei:"../../img/mipmap-mdpi/dingwei.png",
        weizhi:"蜀都中心一期",
        qianmi:"0.1km"
      },
      {
        img:"../../img/mipmap-mdpi/logo.png",
        name:"成都好姐姐陪护服务有限公司",
        title:"以服务1000人",
        dingwei:"../../img/mipmap-mdpi/dingwei.png",
        weizhi:"蜀都中心一期",
        qianmi:"0.1km"
      },
    ],
    evaluate:[
      {
        img:"../../img/mipmap-mdpi/hugong.png",
        name:"咖啡时光",
        timer:"2021.8.20",
        pingjia:"王阿姨非常的专业王阿姨非常的专业王阿姨非常的专业王阿姨非常的专业王阿姨非常的专业",
        chart:[
          {
            imag:"../../img/mipmap-mdpi/bingren.png"
          },
          {
            imag:"../../img/mipmap-mdpi/bingren.png"
          },
          {
            imag:"../../img/mipmap-mdpi/bingren.png"
          },
        ],
        imm:"../../img/mipmap-mdpi/hugong.png",
        namm:"王阿姨"
      },
      {
        img:"../../img/mipmap-mdpi/hugong.png",
        name:"咖啡时光",
        timer:"2021.8.20",
        pingjia:"王阿姨非常的专业王阿姨非常的专业王阿姨非常的专业王阿姨非常的专业王阿姨非常的专业",
        imm:"../../img/mipmap-mdpi/hugong.png",
        namm:"王阿姨"
      },
      {
        img:"../../img/mipmap-mdpi/hugong.png",
        name:"咖啡时光",
        timer:"2021.8.20",
        pingjia:"王阿姨非常的专业王阿姨非常的专业王阿姨非常的专业王阿姨非常的专业王阿姨非常的专业",
        imm:"../../img/mipmap-mdpi/hugong.png",
        namm:"王阿姨"
      },
      {
        img:"../../img/mipmap-mdpi/hugong.png",
        name:"咖啡时光",
        timer:"2021.8.20",
        pingjia:"王阿姨非常的专业王阿姨非常的专业王阿姨非常的专业王阿姨非常的专业王阿姨非常的专业",
        imm:"../../img/mipmap-mdpi/hugong.png",
        namm:"王阿姨"
      },
      {
        img:"../../img/mipmap-mdpi/hugong.png",
        name:"咖啡时光",
        timer:"2021.8.20",
        pingjia:"王阿姨非常的专业王阿姨非常的专业王阿姨非常的专业王阿姨非常的专业王阿姨非常的专业",
        imm:"../../img/mipmap-mdpi/hugong.png",
        namm:"王阿姨"
      },
    ]
  },
  /**
   * 组件的方法列表
   */
  methods: {
    goto(e) {
      this.setData({
        flag:e.currentTarget.dataset.index
      })
    },
    // 去用户评价详情
    Userpraise(){
      wx.navigateTo({
        url: '/pages/Praise/Praise',
      })
    },
    //去护工详情页
    godetaild(){
      wx.navigateTo({
        url: '/pages/details/details',
      })
    },
    //去机构详情页
    goorgandetail(){
        let id = 0
        wx.navigateTo({
          url: `/pages/details/details?id=${id}`,
        })
    },
    Discoloration(e){
      this.setData({
        flagIndex:e.currentTarget.dataset.index
      })
    }
  }
})
